### ISSUE TITLE
Suggestion: Full configurability

### ISSUE THREAD

**Issue by Dylan4ever** [MinecraftBoomMod/Minecraft-Boom#2]
Minecraft Boom seems similar to Quark in many regards, so I was wondering if it wouldn't be a good idea to provide a similar amount of configurability? The ability to turn off everything seperately would be, quite frankly, amazing.

Also, you asked me ages ago on the MCF if you could use some of the ideas I had for Nether improvements, not sure if you remember. How's that coming along :)?

**Comment by Spazmunki13** [comment]
I would like to second this! It would be very useful to be able to manage the things added by this mod. :)

**Comment by Soupbubbles** [comment]
This is being added right now! Will close this for now :)
