### ISSUE TITLE
Another crash after the server has been on for awhile.

### ISSUE THREAD

**Issue by Gbergz** [MinecraftBoomMod/Minecraft-Boom#4]
Using the latest version you fixed so the server can actually start, but now i get this crash message after like 5 minutes online.

Crash Report:
[PASTEBIN LINK](https://pastebin.com/v5Na7cj4)

I don't know what is causing this but i might aswell report it to you. :)

**Comment by Soupbubbles** [comment]
Thanks for the report, working to fix the bug!

**Comment by Soupbubbles** [comment]
Fixed
